# Generated by Django 3.2.9 on 2021-11-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shooble', '0002_auto_20211130_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='numberOfLikes',
            field=models.IntegerField(default=0),
        ),
    ]
