# Generated by Django 3.2.9 on 2021-11-30 20:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shooble', '0004_likedposts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikedPosts',
            new_name='LikedPost',
        ),
    ]
