# Generated by Django 3.2.9 on 2021-12-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shooble', '0006_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepic',
            name='user',
        ),
        migrations.AddField(
            model_name='profilepic',
            name='title',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
