# Generated by Django 3.2.9 on 2021-12-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shooble', '0008_profilepic_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepic',
            name='user',
        ),
        migrations.AddField(
            model_name='profilepic',
            name='userID',
            field=models.IntegerField(default=None),
        ),
    ]
