# Generated by Django 3.2.9 on 2021-12-03 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shooble', '0012_alter_profilepic_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepic',
            name='title',
        ),
    ]
