# Generated by Django 3.2.9 on 2021-12-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shooble', '0013_remove_profilepic_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='profile_pic',
            field=models.ImageField(default='/media/images/defaultProfilePic.jpeg', upload_to='images'),
        ),
    ]
