# Generated by Django 3.2.9 on 2021-12-04 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shooble', '0014_alter_profilepic_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='textBody',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profilepic',
            name='profile_pic',
            field=models.ImageField(default=None, upload_to='images'),
        ),
        migrations.CreateModel(
            name='UserBio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(default=None, max_length=256)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
